### ISSUE TITLE
Password input functionality? 

### ISSUE THREAD

**Issue by sigboe** [Shizcow/dmenu-rs#1]
I run dmenu with a patch that allows passwords to be inputted by having a -P option. I use this for pinentry and graphical sudo. With the -P option input is showed as only periods:  ........ 

Do you have this function?

**Comment by Shizcow** [comment]
Currently, this is the same as dmenu with no patches, but I'll consider adding. Do you have a source for the patch so I can get the feature correct?

**Comment by sigboe** [comment]
http://tools.suckless.org/dmenu/patches/password/

**Comment by Shizcow** [comment]
Thanks. I'll rearrange some things and push out a change within the next day or so.

**Comment by sigboe** [comment]
Great I'll be looking forward to try this then :)

**Comment by Shizcow** [comment]
Update on this issue:

The functionality exists on master now. The reason for the delay is that I've been developing several Rust crates to facilitate writing plugins. My goal is to make plugin writing as painless of an experience as possible, and so far it looks great.

Features are still in development. Tasks yet to be completed are:
1) Automatic manpage generation based on plugins
2) Expose more to plugins for increased potential

I expect to bring these features to master shortly so that more plugins can be written cleanly and quickly.

I'm leaving this issue open for now because, as mentioned above, manpage generation is not yet complete.

**Comment by Shizcow** [comment]
Manpage generation is complete, and password input functionality has been fully implemented.
