### ISSUE TITLE
Generate a new cache file

### ISSUE THREAD

**Issue by ghost** [Shizcow/dmenu-rs#65]
It would be nice if the .cache/dmenu_run file was regenerated if it doesnt exist rather than throwing out an error.

**Comment by benjaminedwardwebb** [comment]
This issue is fixed as of `5.5.3`.

You can use [this NixOS overlay][0] while we wait for https://github.com/NixOS/nixpkgs/pull/268547 to merge and close https://github.com/NixOS/nixpkgs/issues/293164.

The details of why you see this behavior are a little complicated, but if
you're interested you can dig into some prior PRs and their commit messages.

- https://github.com/Shizcow/dmenu-rs/pull/56
- https://github.com/Shizcow/dmenu-rs/pull/57
- https://github.com/Shizcow/dmenu-rs/pull/57/commits/3e4fd34b70e9416ed40963dab74035807b61ea16

I don't know if `5.5.3` will also fix https://github.com/Shizcow/dmenu-rs/issues/64 but it's worth a try.

[0]: https://github.com/Shizcow/dmenu-rs/issues/62#issuecomment-1817738443

**Comment by ghost** [comment]
Interestingly, I already tried switching to the `5.5.3` version yesterday and seemed to have the same issues even after a reboot but today its working fine. Wonder what that is about. [#64](https://github.com/Shizcow/dmenu-rs/issues/64) seems to also be a non-issue now.
