### ISSUE TITLE
calc plugin crashes on certain keystroke

### ISSUE THREAD

**Issue by brandonsandoval** [Shizcow/dmenu-rs#7]
In a particular situation for me, dmenu running in calculator mode AND along with this particular font "xos4 Terminus-14" (maybe fonts containing a space?), crashes when the FIRST key pressed is the menu is the lowercase "m" character. 

```dmenu_run --calc --font "xos4 Terminus-14"```

```
thread 'main' panicked at 'assertion failed: self.is_char_boundary(new_len)', /build/rust/src/rustc-1.44.1-src/src/libcore/macros/mod.rs:34:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I am using Arch linux with i3wm.

**Comment by Shizcow** [comment]
I am able to reproduce this error, with a similar panic message. I'll do some digging to find out why.

**Comment by Shizcow** [comment]
The issue has been located and fixed. When truncating text with ellipses (`...`), Strings were being truncated on byte boundaries instead of char boundaries. The definition provided by `rink-rs` had unicode `THIN-SPACE` present. Because `THIN-SPACE.len() > THIN-SPACE.chars().count()`, the panic occurred. 

Now, Strings are truncated on grapheme boundaries. This should be even further resilient against unicode errors than char boundaries.

**Comment by brandonsandoval** [comment]
Thanks for the fast fix

**Comment by Shizcow** [comment]
Not a problem. Thanks for finding so many good issues today.
